### ISSUE TITLE
Not working with Node 14 Latest version (and With Node 10.15 local installation 404 issue)| Platform: Fedora 31

### ISSUE THREAD

**Issue by sumitkumar2019** [AntlerVC/firetable#188]
I tried the required steps to install this project locally and realise that it is compatible with Node 10.15 not with the latest stable versions. Please have a look. On Node 10.15 also, after installation I am getting 404 for localhost:5000

**Comment by notsidney** [comment]
Hi, could you please write the error you received that made you think it’s incompatible with specific versions of node? We have tested it on Node 10.20.1 and 14.9.0 with no issues. Additionally, there shouldn’t be anything that causes it to be incompatible with any versions of Node 10 or above.

If you got a 404 issue running `firetable serve` (which launches a dev server at localhost:5000), then the build of Firetable likely failed. Please check there is something in the `www/build` folder.

I noticed you had posted another issue, which was caused by using npm to install dependencies and not yarn. This likely caused the build to fail. Please use yarn. We do not say to use npm to install dependencies anywhere in the instructions and if you used the Firetable CLI, it would have used yarn.

**Comment by notsidney** [comment]
Hi, please use a Node version between 10 and 12. There is an issue with [Firebase’s dependencies requiring a version of grpc](https://github.com/grpc/grpc-node/issues/888#issuecomment-516918993) that [do not support Node 13 and above](https://github.com/grpc/grpc-node/issues/1216#issuecomment-564656929).

If you got a 404 issue running `firetable serve` (which launches a dev server at localhost:5000), then the build of Firetable likely failed. Please check there is something in the `www/build` folder.

I noticed you had posted another issue, which was caused by using npm to install dependencies and not yarn. This likely caused the build to fail. Please use yarn. We do not say to use npm to install dependencies anywhere in the instructions and if you used the Firetable CLI, it would have used yarn.
