### ISSUE TITLE
Document Select Field - Algolia integration

### ISSUE THREAD

**Issue by kristiankyvik** [AntlerVC/firetable#196]
I have added the API Keys for algolia as well as created an index. I am trying to add Document Select field to my table in firetable, but I cannot get it to work. The dropdown just loads for ever when I click on it.

What I want is to be able to link a row in one table to a specific row of another table, establishing a relationship (a la foreign key). Is this possible?

**Comment by shamsmosowi** [comment]
hi Kristian!, yes Document Select can help with establishing a relationship as it stores docPath and snapshot of the selected row in the field/cell. 
It is not clear how it works at the moment and we'll be adding functionality to help with the setup and creating the index on Algolia soon.
let me try document the setup for its here, and let me know if you are still having any issues with getting it to work:

- check to make sure you have the` www/.env` file with the correct values for `REACT_APP_ALGOLIA_APP_ID` and `REACT_APP_ALGOLIA_SEARCH_API_KEY`
- You'll need to have a table set up on firetable for the collection that is indexed on Algolia
- in the column menu, select `Column Settings` and specify the table that is connected to the Aloglia index collection, and specify the primary keys(these are used for the label of the results and the selected items). Optionally you can add filter string so that it only shows a subset of the records on Algolia
![image](https://user-images.githubusercontent.com/13803906/92856127-706fae00-f436-11ea-8609-772d7dee5268.png)

**Comment by kristiankyvik** [comment]
Hi @shamsmosowi,

Thanks for taking the time to explain this. I followed the instructions and managed to get it working! 

Super impressed by the tool, keep up the good work!

**Comment by kristiankyvik** [comment]
Hi @shamsmosowi,
I have a follow up question, on how to use these field types (object reference). I have an examples where I have companies that have buildings ( buildings only have one unique company). With the fire table setup, I have added a a reference to a company on the building objects. This works nicely on fire table but when I try to fetch this data in my app, I am having difficulties finding a good way of querying all buildings with company = company id, since there are challenges with performing filters on nested sub attributes of object that are in a sub collection. 

Any tips on how you have solved this in antler?

**Comment by shamsmosowi** [comment]
Hi @kristiankyvik , it really depends on how you are viewing that data in your app. 
If the number of buildings is not too large, and you are only viewing one company's buildings at a time, you could store the building as an array in the company doc(as you have 1mb of capacity here).
If you have a lot of buildings, the amount of data in the building object is too large, or you need different access permissions, then you should store it in a sub-collection. If you do need to perform complex queries on the frontend and can't just compose an index for the buildings sub/group collections, then you should probably sync it to algloia, and give your app a restricted API key to the buildings index. We have [algolia cloud functions](https://github.com/AntlerVC/firetable/blob/master/cloud_functions/functions/src/algolia/index.ts) to help with indexing/syncing but their use is not documented yet.
