### ISSUE TITLE
Cannot undo "isCollectionGroup" toggle action

### ISSUE THREAD

**Issue by kristiankyvik** [AntlerVC/firetable#206]
When I create a new table, I decide to make it a collection group table, by toggling the isCollectionGroup toggle. 
![image](https://user-images.githubusercontent.com/6661158/93705973-50b94380-fb22-11ea-9d89-b2cdb73b13c7.png)
When I try to edit the general settings of this table, the toggle does not appear to be activated, not reflecting the fact that this is a collection group. At the same time, I cannot undo the action to restore the table to a normal collection table.

**Comment by shamsmosowi** [comment]
thanks @kristiankyvik  for flagging this, @dorukde I think the UI for this needs improvement, it's not actually possible to switch easily between the two types of tables due to the different table scheme types. We will need a different way of specifying the table type on creation, which is not reversible.

**Comment by dorukde** [comment]
thanks @kristiankyvik & @shamsmosowi, I have added a new modal view for the Edit (create view has no disabled states). 
![Lab: Editing created table](https://user-images.githubusercontent.com/20957578/93736844-ed640a00-fc24-11ea-9ae1-78c9f529d9b3.png)

**Comment by kristiankyvik** [comment]
Hi @dorukde, thanks for the quick reply! The solution looks good!

**Comment by shamsmosowi** [comment]
#240
