### ISSUE TITLE
Subtables require cloud function?

### ISSUE THREAD

**Issue by jfr3000** [AntlerVC/firetable#286]
**Describe the bug**
I am trying to include a subcollection as a subtable. I can add the column, but when following the link, I am getting the "You don't have permissions to see the results." error message. I can see there is a request to `cloudfunctions.net/callable-setFiretablePersonalizedFilter`, but I don't have cloud functions enabled for my project. Is that necessary? The other columns are working fine.

**To Reproduce**
1. Create a firebase project without cloud functions enabled.
2. Add a table and a column for a subtable.
3. Follow the subtable link
4. See the permission error message

**Comment by shamsmosowi** [comment]
Hi juila, the cloud function is not required. You need to make sure your firestore rules allow access to the subcollection. The current firetable behaviour is if the firestore rules rejects a request due to insufficient permission, firetable calls ```callable-setFiretablePersonalizedFilter``` cloud function to provide the query filters for the logged in user that would be permitted by firestore rules. This function is not included in the repo because it's heavily dependent on how your project is structured, happy to provide a template of it if you'd like.

**Comment by jfr3000** [comment]
Ah, thanks for the quick response! I must be making some silly mistake about the subcollection rule then. I _think_ I have them set correctly, but apparently not. Will keep poking around. Thanks for the great project!

**Comment by jfr3000** [comment]
(this turned out to be a typo in the field name :facepalm: )
